excerpt_separator: "<!--more-->"
markdown: kramdown
paginate: 20

name: Блог Романа Ворушина
url: https://vorushin.github.io
author: Roman Vorushin (roman.vorushin@gmail.com)

# jekyll-seo-tag
title: Блог Романа Ворушина, программирование, AI и жизнь
description: Блог о программировании, искусственном интеллекте, машинном обучении, нейронных сетях, жизни в Швейцарии, работе в Google. AI, ML, Deep Learning insights.
twitter:
  username: vorushin
social:
  name: Roman Vorushin
  links:
    - https://x.com/vorushin
    - https://github.com/vorushin
    - https://www.linkedin.com/in/vorushin/
lang: ru_RU

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
