excerpt_separator: "<!--more-->"
markdown: kramdown
paginate: 20

name: Roman Vorushin
url: https://vorushin.github.io
author: Roman Vorushin (roman.vorushin@gmail.com)

# jekyll-seo-tag
title: Roman Vorushin
description: Blog about artificial intelligence, machine learning, LLM training, neural networks, and life. Research Engineer at Google DeepMind working on Gemini.
twitter:
  username: vorushin
social:
  name: Roman Vorushin
  links:
    - https://x.com/vorushin
    - https://github.com/vorushin
    - https://www.linkedin.com/in/vorushin/
lang: en

plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# Default language and layout for existing posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      lang: ru
      layout: post
