excerpt_separator: "<!--more-->"
markdown: kramdown
paginate: 20

name: Блог Романа Ворушина
url: vorushin.ru
author: Roman Vorushin (roman.vorushin@gmail.com)
rss_path: feeds/entries/
rss_name: index.html
rss_post_limit: 20

gems:
  - jekyll-redirect-from